### ISSUE TITLE
Plugin is saying that I'm tracking ignored files but it's wrong

### ISSUE THREAD

**Issue by kevincam3** [hsz/idea-gitignore#523]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
After I open a project the plugin presents a popup in the lower right corner that tells me "Ignored files found that are tracked" I click the "Show details" button to see the files and I notice that it's listing files that while they are listed in the .gitignore file they are being excluded from being ignored so they should not be counted as files that are being ignored in .gitignore

```
Stack trace if available.
```

### Steps to Reproduce

Just logging in produces the pop up. I've proved a screenshot so you can see the problem

**Expected behavior:** _What you expect to happen_
To not display this popup message

**Actual behavior:** _What actually happens_
Displays this popup message

**Reproduces how often:** _What percentage of the time does it reproduce?_
100%

### Versions

**Plugin:** 
Version: 2.4.0
```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 
2017.3.4
```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 
Windows 10 Pro
```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._
![image](https://user-images.githubusercontent.com/870934/37100455-c066045e-2201-11e8-92b9-75c3ebf925e7.png)

**Comment by chaimleib** [comment]
I'm having the same issue on macOS.

**Plugin:** 2.6.1
**IDE:** 2018.1.2
**OS:** macOS 10.12.6

![image](https://user-images.githubusercontent.com/7785285/39216001-e4b13f98-47ce-11e8-9f02-b25f30ed306f.png)

**Comment by chaimleib** [comment]
Maybe related: #513

**Comment by chaimleib** [comment]
I tried deleting `.idea/` and launching IntelliJ again (as in #478), but that did not help.

**Comment by kevincam3** [comment]
I think the line you have in your gitignore file "experiments/bin/gen/" ignores the whole folder so the line after it "!experiments/bin/gen/__init___.py" doesn't do anything and that's why it's still being ignored.

I would suggest changing "experiments/bin/gen/" to "experiments/bin/gen/*" and that might fix the problem.

**Comment by mlsquires** [comment]
Same issue. Easy to repo:
mkdir out
touch out/ignored
touch out/.keep

create a .gitignore with the following content:
out/
!.keep

Git (correctly) shows that out/ignored is ignored and out/.keep is not ignored. The plugin appears to not process the "exclusion" operation ("!<something>")

**Comment by jpickwell** [comment]
There's been a change in how Git interprets `.gitignore` files.
[gitignore Pattern Format](https://git-scm.com/docs/gitignore#_pattern_format)
>An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. **It is not possible to re-include a file if a parent directory of that file is excluded.** Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".

So the following no longer works:
```
out/
# doesn't work
!.keep
# also doesn't work
!out/.keep
```

Running `git status` won't show `out/` under "Untracked files:". If you try `git add out/.keep` you'll get this message:
```
The following paths are ignored by one of your .gitignore files:
log/.keep
Use -f if you really want to add them.
```

To correct this you have to stop excluding the directory, and only exclude the contents.
```
out/*
# now this works
!.keep
# and this also works
!out/.keep
```

Running `git status` will now show `out/` directory under "Untracked files:". Running `git add out/.keep` will succeed.

**Comment by hsz** [comment]
This feature will be disabled with v3.1.0
